[package]
name = "deeb_core"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
anyhow = "1.0.86"
log = "0.4.21"
fs2 = "0.4.3"
uuid = { version= "1.8.0", features = ["v4"] }
